//! Fuzz-with-oracle oracle (`@fuzz`) — coverage-guided + SMT oracle.
//!
//! § SPEC    : `specs/23_TESTING.csl` § oracle-modes • fuzz-with-oracles +
//!             `specs/20_SMT.csl` refinement-oracle.
//! § ROLE    : coverage-guided fuzzing (AFL++/libFuzzer-style); inputs constrained by
//!             refinement-types; SMT oracle verifies output-refinement holds.
//! § BUDGET  : 10 min / module in `nightly-extended` per §§ 23 schedule.
//! § STATUS  : T11-phase-2b live (dumb-mode LCG-driven byte-fuzzer with panic-catch
//!             + greedy-shrinker). Coverage-guidance + SMT-oracle hookup deferred to
//!             T11-phase-2c (needs sancov-like harness + cssl_smt closure).

use crate::property::Lcg;
use core::time::Duration;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::time::Instant;

/// Config for the `@fuzz` oracle.
#[derive(Debug, Clone)]
pub struct Config {
    /// Time budget for fuzzing (§§ 23 default 600s in nightly).
    pub budget: Duration,
    /// If `true`, SMT-oracle verifies refinement on every input.
    pub smt_oracle: bool,
    /// Target throughput per-second (for CI regression on fuzz infrastructure).
    pub min_exec_per_sec: u32,
    /// Deterministic seed for the LCG-driven byte-corpus generator.
    pub seed: u64,
    /// Maximum generated-input length in bytes. Default 1024.
    pub max_input_len: usize,
    /// Shrink-rounds applied after a failing input is found.
    pub shrink_rounds: u32,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            budget: Duration::from_secs(600),
            smt_oracle: true,
            min_exec_per_sec: 1000,
            seed: 0xc551_a770_c551_a770_u64,
            max_input_len: 1024,
            shrink_rounds: 32,
        }
    }
}

/// Outcome of running the `@fuzz` oracle.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    /// Stage0 stub — body populated at T11.
    Stage0Unimplemented,
    /// Fuzzing completed without finding crashes or refinement violations.
    Ok { total_execs: u64 },
    /// Found crashing / UB / refinement-violation input; shrunk form attached.
    Counterexample {
        shrunk_input: String,
        message: String,
    },
}

/// Dispatcher trait for `@fuzz` oracle.
pub trait Dispatcher {
    fn run(&self, config: &Config) -> Outcome;
}

/// Stage0 stub dispatcher — always returns `Stage0Unimplemented`.
#[derive(Debug, Default, Clone, Copy)]
pub struct Stage0Stub;

impl Dispatcher for Stage0Stub {
    fn run(&self, _config: &Config) -> Outcome {
        Outcome::Stage0Unimplemented
    }
}

// ─────────────────────────────────────────────────────────────────────────
// § Live dumb-mode byte-fuzzer : LCG → byte-slice → check-fn (panic-caught).
// ─────────────────────────────────────────────────────────────────────────

/// Run `check` against LCG-generated byte-slices until either the budget is
/// exhausted (`Ok`) or `check` returns `false` / panics (`Counterexample`).
/// On a failing input, greedy-shrinks to the minimum-form that still fails.
///
/// `check` : returns `true` iff the input is acceptable. A return of `false`
/// counts as a refinement-violation ; a panic counts as a crash. Both paths
/// route to `Counterexample`.
///
/// § PANIC-CATCH : `std::panic::catch_unwind` wraps each invocation, so
///   `check`'s panics don't tear down the fuzzer. The message is captured
///   via the panic-hook ; on Rust stable without a custom hook, the message
///   degrades to a generic "panic (details not captured)".
pub fn run_fuzz_dumb<F>(config: &Config, mut check: F) -> Outcome
where
    F: FnMut(&[u8]) -> bool + core::panic::RefUnwindSafe,
{
    let mut rng = Lcg::new(config.seed);
    let deadline = Instant::now() + config.budget;
    let mut total_execs: u64 = 0;

    loop {
        if total_execs % 256 == 0 && Instant::now() >= deadline {
            break;
        }
        let input = generate_bytes(&mut rng, config.max_input_len);
        total_execs += 1;
        let failed = match catch_unwind(AssertUnwindSafe(|| check(&input))) {
            Ok(true) => false,
            Ok(false) | Err(_) => true, // false-return + panic both count as failure
        };
        if failed {
            let shrunk = shrink_input(&input, &mut check, config.shrink_rounds);
            return Outcome::Counterexample {
                shrunk_input: format!("{shrunk:?}"),
                message: format!("fuzz-input failed after {total_execs} execs"),
            };
        }
    }

    Outcome::Ok { total_execs }
}

/// Generate a random byte-slice of length up to `max_len`. Length is drawn
/// from the LCG ; contents are also LCG-driven. Zero-length inputs are
/// possible (0 ≤ len ≤ max_len).
fn generate_bytes(rng: &mut Lcg, max_len: usize) -> Vec<u8> {
    // Avoid skewed distributions by deriving len from a single raw word.
    let raw = rng.next_u64();
    let len = if max_len == 0 {
        0
    } else {
        (raw as usize) % (max_len + 1)
    };
    let mut out = Vec::with_capacity(len);
    for _ in 0..len {
        out.push((rng.next_u64() & 0xff) as u8);
    }
    out
}

/// Greedy shrinker : tries progressively-smaller inputs (by truncation +
/// byte-nulling) and keeps any that still fail under `check`. Halts after
/// `max_rounds` without improvement.
fn shrink_input<F>(start: &[u8], check: &mut F, max_rounds: u32) -> Vec<u8>
where
    F: FnMut(&[u8]) -> bool + core::panic::RefUnwindSafe,
{
    let mut best = start.to_vec();
    let mut round = 0;
    loop {
        if round >= max_rounds {
            break;
        }
        round += 1;
        let candidates = shrink_candidates(&best);
        let mut improved = false;
        for c in candidates {
            let failed = match catch_unwind(AssertUnwindSafe(|| check(&c))) {
                Ok(true) => false,
                Ok(false) | Err(_) => true,
            };
            if failed && c.len() < best.len() {
                best = c;
                improved = true;
                break;
            }
        }
        if !improved {
            break;
        }
    }
    best
}

/// Produce smaller-or-equivalent candidate inputs : truncation-halving +
/// single-byte-removal at key positions.
fn shrink_candidates(bytes: &[u8]) -> Vec<Vec<u8>> {
    let mut out = Vec::new();
    let n = bytes.len();
    if n == 0 {
        return out;
    }
    // Halve from the right.
    out.push(bytes[..n / 2].to_vec());
    // Drop first byte.
    out.push(bytes[1..].to_vec());
    // Drop last byte.
    out.push(bytes[..n - 1].to_vec());
    out
}

#[cfg(test)]
mod tests {
    use super::{run_fuzz_dumb, Config, Dispatcher, Outcome, Stage0Stub};
    use core::time::Duration;

    #[test]
    fn stub_returns_unimplemented() {
        assert_eq!(
            Stage0Stub.run(&Config::default()),
            Outcome::Stage0Unimplemented
        );
    }

    #[test]
    fn always_ok_check_never_finds_counterexample() {
        let config = Config {
            budget: Duration::from_millis(50),
            smt_oracle: false,
            min_exec_per_sec: 0,
            seed: 42,
            max_input_len: 64,
            shrink_rounds: 4,
        };
        let outcome = run_fuzz_dumb(&config, |_bytes| true);
        match outcome {
            Outcome::Ok { total_execs } => assert!(total_execs > 0, "expected > 0 execs"),
            other => panic!("expected Ok, got {other:?}"),
        }
    }

    #[test]
    fn return_false_counts_as_failure() {
        let config = Config {
            budget: Duration::from_secs(1),
            smt_oracle: false,
            min_exec_per_sec: 0,
            seed: 1,
            max_input_len: 32,
            shrink_rounds: 8,
        };
        // Only accept empty inputs → any non-empty is a counterexample.
        let outcome = run_fuzz_dumb(&config, <[u8]>::is_empty);
        assert!(matches!(outcome, Outcome::Counterexample { .. }));
    }

    #[test]
    fn panic_is_caught_as_counterexample() {
        let config = Config {
            budget: Duration::from_secs(1),
            smt_oracle: false,
            min_exec_per_sec: 0,
            seed: 2,
            max_input_len: 32,
            shrink_rounds: 4,
        };
        // Panics on non-empty input.
        let outcome = run_fuzz_dumb(&config, |bytes| {
            assert!(bytes.is_empty(), "non-empty input panics");
            true
        });
        assert!(matches!(outcome, Outcome::Counterexample { .. }));
    }

    #[test]
    fn zero_max_input_len_only_produces_empty_inputs() {
        let config = Config {
            budget: Duration::from_millis(20),
            smt_oracle: false,
            min_exec_per_sec: 0,
            seed: 3,
            max_input_len: 0,
            shrink_rounds: 4,
        };
        // Property : input is always empty (max_input_len=0 forces this).
        let outcome = run_fuzz_dumb(&config, <[u8]>::is_empty);
        assert!(matches!(outcome, Outcome::Ok { .. }));
    }

    #[test]
    fn shrink_reduces_counterexample_size() {
        let config = Config {
            budget: Duration::from_secs(1),
            smt_oracle: false,
            min_exec_per_sec: 0,
            seed: 5,
            max_input_len: 256,
            shrink_rounds: 32,
        };
        // Failure condition : any input of length > 1 (trivially shrinkable to length 1).
        let outcome = run_fuzz_dumb(&config, |bytes| bytes.len() <= 1);
        match outcome {
            Outcome::Counterexample { shrunk_input, .. } => {
                // The shrunk input should be short — the debug-formatted byte-vec
                // of length n takes roughly 5n characters (each byte prints as
                // a comma-separated decimal) — so len = 2 should be under 20 chars.
                assert!(
                    shrunk_input.len() < 40,
                    "expected short shrunk input, got: {shrunk_input}"
                );
            }
            other => panic!("expected Counterexample, got {other:?}"),
        }
    }

    #[test]
    fn zero_budget_still_runs_at_least_once() {
        let config = Config {
            budget: Duration::from_secs(0),
            smt_oracle: false,
            min_exec_per_sec: 0,
            seed: 8,
            max_input_len: 16,
            shrink_rounds: 1,
        };
        let outcome = run_fuzz_dumb(&config, |_bytes| true);
        match outcome {
            // Either Ok after budget check OR we ran once (first iteration is
            // before the deadline-check). Both are acceptable ; only assert
            // no-panic + well-formed outcome.
            Outcome::Ok { .. } | Outcome::Counterexample { .. } => {}
            Outcome::Stage0Unimplemented => panic!("should not be stub"),
        }
    }
}
