import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const read = (path: string): string => readFileSync(resolve(process.cwd(), path), 'utf8');

const page = read('pages/brain.tsx');
const apocryphaPage = read('pages/apocrypha.tsx');
const accountChat = read('components/apocrypha/AccountChat.tsx');
const experience = read('components/brain/BrainExperience.tsx');
const owner = read('lib/brain/owner.ts');
const snapshot = read('pages/api/brain/snapshot.ts');
const runtimeProvider = read('lib/brain/runtime-provider.ts');
const runtimeProxy = read('lib/apocv4/runtime-proxy.ts');
const middleware = read('middleware.ts');
const telemetry = read('lib/akashic-telemetry/client.ts');
const app = read('pages/_app.tsx');
const document = read('pages/_document.tsx');
const consent = read('components/AkashicConsent.tsx');
const home = read('pages/index.tsx');
const shell = read('components/SiteShell.tsx');
const miniBrain = read('lib/brain/mini-brain.ts');
const mobileRelay = read('lib/brain/mobile-relay.ts');
const mobileSync = read('pages/api/brain/mobile/sync.ts');
const mnemeBootstrap = read('pages/api/brain/mneme/bootstrap.ts');
const brainManifest = JSON.parse(read('public/brain-manifest.json')) as Record<string, unknown>;
const brainWorker = read('public/brain-sw.js');
const brainStyles = read('components/brain/BrainExperience.module.css');
const vercelConfig = JSON.parse(read('vercel.json')) as {
  headers?: Array<{ source?: string; headers?: Array<{ key?: string; value?: string }> }>;
};
const playwrightConfig = read('playwright.config.ts');

assert.match(page, /getServerSideProps/, 'Brain page must authorize before render');
assert.match(page, /requireBrainOwner/, 'Brain page must use the owner allowlist boundary');
assert.match(page, /private, no-store/, 'Brain document must be private and non-cacheable');
assert.match(page, /noindex,nofollow,noarchive,nosnippet/, 'Brain page must be crawler-dark');
assert.match(page, /viewport-fit=cover/, 'Brain page must expose iOS safe areas to its installed layout');
assert.match(apocryphaPage, /<AccountChat \/>/, 'primary Apocrypha page must expose the account conversation surface');
assert.match(apocryphaPage, /getServerSideProps/, 'account shell must receive the request nonce instead of static scripts blocked by CSP');
assert.match(apocryphaPage, /owner\.ok && usesOwnerRuntime\(owner\.user\)/, 'owner conversation requires server authorization and the exact configured owner binding');
assert.match(apocryphaPage, /ownerConversation \? <BrainExperience serverAccess="owner" \/> : <AccountChat \/>/, 'both owner routes must share the existing encrypted conversation controller while members keep account chat');
assert.doesNotMatch(accountChat, /href="\/brain"/, 'account conversation must not advertise a competing chat');
assert.match(apocryphaPage, /<title>Apocrypha · Apocky<\/title>/, 'primary route must carry Apocrypha branding');
assert.match(apocryphaPage, /Sign in to your Apocky account/, 'primary route must describe account access honestly');
assert.match(apocryphaPage, /noindex,nofollow,noarchive,nosnippet/, 'primary Apocrypha page must be crawler-dark');
assert.match(apocryphaPage, /viewport-fit=cover/, 'primary Apocrypha page must expose iOS safe areas to its installed layout');
assert.match(accountChat, /\/login\?next=%2Fapocrypha/, 'sign-in must return to the primary Apocrypha route');
assert.match(accountChat, /\/register\?next=%2Fapocrypha/, 'new accounts must return to the primary Apocrypha route');
assert.match(accountChat, /authFetch\('\/api\/mobile\/turn'/, 'account chat must use the authenticated account adapter');
assert.doesNotMatch(accountChat, /\/api\/brain\/|\/api\/apocrypha\//, 'public account chat must not invoke private or retired adapters');
assert.match(owner, /getAdminAuthorization/, 'Brain APIs must derive authority from the server session');
assert.match(owner, /BRAIN_OWNER_REQUIRED/, 'non-owner identities must have a stable denial code');
assert.match(snapshot, /deriveMemberProfileId\(owner\.user\.id\)/, 'snapshot profile must be derived server-side');
assert.doesNotMatch(snapshot, /profile_id:/, 'snapshot must not emit a profile identifier');
assert.match(snapshot, /getMessagesByIds/, 'source references must resolve through the private store');
assert.match(experience, /Memory search uses saved records and does not ask a model/, 'memory help must explain the search source');
assert.match(experience, /<h1>Apocrypha<\/h1>/, 'shared experience must visibly identify Apocrypha');
assert.match(experience, /BrainGraph/, 'graph projection missing');
assert.match(experience, /Timeline/, 'timeline projection missing');
assert.match(experience, /Tunnel/, 'source tunnel missing');
assert.match(experience, /sourceMessages\(memory, messages\)/, 'tunnel must bind memory source IDs to message records');
assert.doesNotMatch(experience, /\/api\/mneme\//, 'browser must use only owner-authorized Brain APIs');
assert.doesNotMatch(experience, /ANTHROPIC|VOYAGE|retrievePipeline/, 'new Brain turns must not invoke paid model paths');
assert.match(runtimeProvider, /submitOwnerBrainRuntimeChat/, 'conversation must use the validated local runtime adapter');
assert.match(runtimeProxy, /APOCKY_BRAIN_LOCAL_PROVIDER_ENABLED/, 'local runtime needs an explicit scoped enable gate');
assert.match(runtimeProxy, /owner-brain/, 'runtime bypass must be scoped to the Brain adapter');
assert.match(middleware, /request\.nextUrl\.pathname === '\/brain'/, 'middleware must recognize the private page');
assert.match(middleware, /request\.nextUrl\.pathname === '\/apocrypha'/, 'middleware must recognize the primary private alias');
assert.match(telemetry, /pathname === '\/brain'/, 'private page must be a telemetry blackout');
assert.match(telemetry, /pathname === '\/apocrypha'/, 'primary private alias must be a telemetry blackout');
assert.match(consent, /if \(blackout \|\| compactSurface\) return null/, 'telemetry-blackout pages must not receive a fixed diagnostics control over the private PWA');
assert.match(app, /pathname === '\/apocrypha'/, 'primary private alias must render without the public site shell');
assert.match(app, /privateBrainSurface[\s\S]*?href="\/manifest\.json"/, 'the public manifest must be route-aware across client navigation');
assert.doesNotMatch(document, /rel="manifest"/, 'the fixed document head must not pin the public manifest onto the private PWA');
assert.match(home, /href: '\/apocrypha'/, 'home must expose Apocrypha to every visitor');
assert.doesNotMatch(home, /OWNER-PRIVATE|public relay remains closed/, 'home must not retain the superseded owner-only promise');
assert.match(shell, /href: '\/apocrypha', label: 'Apocrypha'/, 'public shell must reveal account chat');
assert.doesNotMatch(shell, /href="\/brain"/, 'public navigation must lead to the canonical conversation rather than a competing owner chat');
assert.doesNotMatch(experience, /Mini Brain · deterministic|Local cortex capability|useful Mini Brain|Reflect \+ queue/, 'placeholder replies and model capability marketing must be absent');
assert.match(experience, /message\.origin !== 'local-reflection'/, 'legacy reflections stay out of the active conversation');
assert.match(experience, /Queue message/, 'offline composition must explicitly queue for desktop delivery');
assert.match(experience, /desktop remains authoritative/i, 'mobile topology must name desktop authority');
assert.match(experience, /Retry on current history/, 'cursor conflict requires an explicit owner rebase');
assert.match(experience, /Create my private memory profile/, 'missing Mneme profile needs an explicit owner action');
assert.match(experience, /CREATE_OWNER_PRIVATE_MNEME_PROFILE/, 'profile bootstrap must carry an exact confirmation value');
assert.match(miniBrain, /AES-GCM/, 'recent local state must be encrypted');
assert.match(miniBrain, /extractable|false,[\s\S]*?\['sign', 'verify'\]/, 'device private signing key must be non-exportable');
assert.doesNotMatch(miniBrain, /deterministicMiniBrainReply|probeMiniBrainCortex/, 'queued turns cannot synthesize a placeholder assistant response');
assert.doesNotMatch(miniBrain, /snapshot\.messages/, 'offline memory cache must not copy raw Mneme source messages');
assert.match(miniBrain, /pendingLocalMessages/, 'a remote cursor conflict must not hide the still-queued local turn');
assert.match(mobileRelay, /ECDSA/, 'relay must verify the device signature');
assert.match(mobileRelay, /BRAIN_SYNC_REPLAY_REJECTED/, 'relay must reject sequence rewrites');
assert.match(mobileSync, /BRAIN_SYNC_CONFLICT/, 'relay must stop on a stale desktop cursor');
assert.match(mobileSync, /idempotent_replay/, 'relay must recognize an already-committed request id');
assert.match(mnemeBootstrap, /requireBrainOwner/, 'profile bootstrap must require the verified owner allowlist');
assert.match(mnemeBootstrap, /deriveMemberProfileId\(owner\.user\.id\)/, 'profile bootstrap identity must be server-derived');
assert.match(mnemeBootstrap, /BRAIN_MNEME_PROFILE_BINDING_MISMATCH/, 'profile bootstrap must refuse an existing mismatched binding');
assert.doesNotMatch(mnemeBootstrap, /profile_id:/, 'profile bootstrap must not return the opaque profile id');
assert.equal(brainManifest.id, '/brain', 'installed Mini Brain identity is the private route');
assert.equal(brainManifest.start_url, '/brain?source=installed-mini-brain', 'installed Mini Brain opens the private route');
assert.equal(brainManifest.scope, '/brain', 'installed Mini Brain must not contain public account or login pages');
assert.equal(brainManifest.display, 'standalone', 'installed Mini Brain must expose a standalone PWA display mode');
const brainIcons = brainManifest.icons as Array<Record<string, unknown>>;
for (const [size, purpose] of [['192x192', 'any'], ['512x512', 'any'], ['192x192', 'maskable'], ['512x512', 'maskable']] as const) {
  const icon = brainIcons.find(candidate => candidate.sizes === size && candidate.purpose === purpose);
  assert(icon, `manifest needs a ${size} ${purpose} icon`);
  const relativePath = String(icon.src).replace(/^\//u, '');
  const iconPath = resolve(process.cwd(), 'public', relativePath);
  assert(existsSync(iconPath), `manifest icon is missing: ${relativePath}`);
  const bytes = readFileSync(iconPath);
  assert.equal(bytes.subarray(1, 4).toString('ascii'), 'PNG', `${relativePath} must be a PNG`);
  const [expectedWidth, expectedHeight] = size.split('x').map(Number);
  assert.equal(bytes.readUInt32BE(16), expectedWidth, `${relativePath} width drifted`);
  assert.equal(bytes.readUInt32BE(20), expectedHeight, `${relativePath} height drifted`);
}
assert.match(brainWorker, /url\.pathname\.startsWith\('\/api\/'\)\) return/, 'service worker must never cache private API responses');
assert.match(brainWorker, /url\.pathname === '\/brain'/, 'service worker may cache only the private route shell');
assert.doesNotMatch(brainWorker, /\/apocrypha/, 'private worker must not intercept the public account page');
assert.match(miniBrain, /scope: '\/brain'/, 'private worker registration must exclude public pages');
assert.doesNotMatch(brainWorker, /clients\.claim/, 'service worker must not seize the first owner page before its authenticated requests complete');
assert(
  brainWorker.indexOf("url.pathname.startsWith('/api/')") < brainWorker.indexOf('event.respondWith'),
  'private API requests must exit before any service-worker response or cache path',
);
assert.match(experience, /iPhone: Share → Add to Home Screen/, 'iOS needs truthful manual installation guidance');
for (const inset of ['top', 'right', 'bottom', 'left']) {
  assert.match(brainStyles, new RegExp(`safe-area-inset-${inset}`), `installed layout must account for the ${inset} safe-area inset`);
}
const workerHeaders = vercelConfig.headers?.find(entry => entry.source === '/brain-sw.js')?.headers ?? [];
assert(workerHeaders.some(header => header.key === 'Service-Worker-Allowed' && header.value === '/'), 'deployed worker must retain root-scope permission');
assert.match(playwrightConfig, /process\.env\.BRAIN_E2E_OWNER === '1'/, 'owner browser fixtures must remain explicitly opt-in');
assert.match(playwrightConfig, /ownerBrainFixtureEnabled[\s\S]*?LAZARUS_TEST_AUTH_BYPASS: '1'[\s\S]*?APOCKY_ADMIN_EMAILS: 'owner@example\.com'/, 'the local owner matrix must cross both the test-auth and owner-allowlist boundaries');

console.log('brain-page.test : OK · owner gate + private projections + installable encrypted Mini Brain + signed sync seam');
