import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const read = (path: string): string => readFileSync(resolve(process.cwd(), path), 'utf8');

const page = read('pages/brain.tsx');
const apocryphaPage = read('pages/apocrypha.tsx');
const experience = read('components/brain/BrainExperience.tsx');
const owner = read('lib/brain/owner.ts');
const snapshot = read('pages/api/brain/snapshot.ts');
const runtimeProvider = read('lib/brain/runtime-provider.ts');
const runtimeProxy = read('lib/apocv4/runtime-proxy.ts');
const middleware = read('middleware.ts');
const telemetry = read('lib/akashic-telemetry/client.ts');
const app = read('pages/_app.tsx');
const home = read('pages/index.tsx');
const shell = read('components/SiteShell.tsx');
const miniBrain = read('lib/brain/mini-brain.ts');
const mobileRelay = read('lib/brain/mobile-relay.ts');
const mobileSync = read('pages/api/brain/mobile/sync.ts');
const mnemeBootstrap = read('pages/api/brain/mneme/bootstrap.ts');
const brainManifest = JSON.parse(read('public/brain-manifest.json')) as Record<string, unknown>;
const brainWorker = read('public/brain-sw.js');

assert.match(page, /getServerSideProps/, 'Brain page must authorize before render');
assert.match(page, /requireBrainOwner/, 'Brain page must use the owner allowlist boundary');
assert.match(page, /private, no-store/, 'Brain document must be private and non-cacheable');
assert.match(page, /noindex,nofollow,noarchive,nosnippet/, 'Brain page must be crawler-dark');
assert.match(apocryphaPage, /getServerSideProps/, 'primary Apocrypha page must authorize before render');
assert.match(apocryphaPage, /requireBrainOwner/, 'primary Apocrypha page must use the same owner allowlist boundary');
assert.match(apocryphaPage, /<BrainExperience serverAccess=\{serverAccess\} \/>/, 'primary route must render the existing Brain experience');
assert.match(apocryphaPage, /<title>Apocrypha · Apocky<\/title>/, 'primary route must carry Apocrypha branding');
assert.match(apocryphaPage, /Persistent owner-private Apocrypha conversation/, 'primary route must describe its private conversation honestly');
assert.match(apocryphaPage, /private, no-store/, 'primary Apocrypha document must be private and non-cacheable');
assert.match(apocryphaPage, /noindex,nofollow,noarchive,nosnippet/, 'primary Apocrypha page must be crawler-dark');
assert.match(apocryphaPage, /destination: '\/login\?next=%2Fapocrypha'/, 'sign-in must return to the primary Apocrypha route');
assert.match(apocryphaPage, /apple-mobile-web-app-capable" content="yes"/, 'primary route must opt into the iOS installed surface');
assert.match(owner, /getAdminAuthorization/, 'Brain APIs must derive authority from the server session');
assert.match(owner, /BRAIN_OWNER_REQUIRED/, 'non-owner identities must have a stable denial code');
assert.match(snapshot, /deriveMemberProfileId\(owner\.user\.id\)/, 'snapshot profile must be derived server-side');
assert.doesNotMatch(snapshot, /profile_id:/, 'snapshot must not emit a profile identifier');
assert.match(snapshot, /getMessagesByIds/, 'source references must resolve through the private store');
assert.match(experience, /CONTEXTUAL RECALL · NO MODEL CALL/, 'contextual recall must disclose its deterministic path');
assert.match(experience, /<p>OWNER-PRIVATE BRAIN<\/p><h1>Apocrypha<\/h1>/, 'shared experience must visibly identify Apocrypha');
assert.match(experience, /BrainGraph/, 'graph projection missing');
assert.match(experience, /Timeline/, 'timeline projection missing');
assert.match(experience, /Tunnel/, 'source tunnel missing');
assert.match(experience, /sourceMessages\(memory, messages\)/, 'tunnel must bind memory source IDs to message records');
assert.doesNotMatch(experience, /\/api\/mneme\//, 'browser must use only owner-authorized Brain APIs');
assert.doesNotMatch(experience, /ANTHROPIC|VOYAGE|retrievePipeline/, 'new Brain turns must not invoke paid model paths');
assert.match(runtimeProvider, /submitOwnerBrainRuntimeChat/, 'conversation must use the validated local runtime adapter');
assert.match(runtimeProxy, /APOCKY_BRAIN_LOCAL_PROVIDER_ENABLED/, 'local runtime needs an explicit scoped enable gate');
assert.match(runtimeProxy, /owner-brain/, 'runtime bypass must be scoped to the Brain adapter');
assert.match(middleware, /request\.nextUrl\.pathname === '\/brain'/, 'middleware must recognize the private page');
assert.match(middleware, /request\.nextUrl\.pathname === '\/apocrypha'/, 'middleware must recognize the primary private alias');
assert.match(telemetry, /pathname === '\/brain'/, 'private page must be a telemetry blackout');
assert.match(telemetry, /pathname === '\/apocrypha'/, 'primary private alias must be a telemetry blackout');
assert.match(app, /pathname === '\/apocrypha'/, 'primary private alias must render without the public site shell');
assert.match(home, /access === 'owner'[\s\S]*?href: '\/apocrypha'/, 'home must send owner access to the primary Apocrypha route');
assert.match(home, /href: authenticated \? '\/apocrypha' : '\/login\?next=%2Fapocrypha'/, 'home sign-in must return to the primary route');
assert.match(shell, /access === 'owner'.*href="\/apocrypha"/, 'shell must reveal the primary route only after owner authorization');
assert.match(experience, /Mini Brain · deterministic/, 'offline response must not impersonate learned Apocrypha');
assert.match(experience, /desktop remains authoritative/i, 'mobile topology must name desktop authority');
assert.match(experience, /Retry on current history/, 'cursor conflict requires an explicit owner rebase');
assert.match(experience, /Create my private memory profile/, 'missing Mneme profile needs an explicit owner action');
assert.match(experience, /CREATE_OWNER_PRIVATE_MNEME_PROFILE/, 'profile bootstrap must carry an exact confirmation value');
assert.match(miniBrain, /AES-GCM/, 'recent local state must be encrypted');
assert.match(miniBrain, /extractable|false,[\s\S]*?\['sign', 'verify'\]/, 'device private signing key must be non-exportable');
assert.match(miniBrain, /NO_VERIFIED_LOCAL_MODEL_ARTIFACT/, 'unavailable learned cortex must remain typed and truthful');
assert.doesNotMatch(miniBrain, /snapshot\.messages/, 'offline memory cache must not copy raw Mneme source messages');
assert.match(miniBrain, /pendingLocalMessages/, 'a remote cursor conflict must not hide the still-queued local turn');
assert.match(mobileRelay, /ECDSA/, 'relay must verify the device signature');
assert.match(mobileRelay, /BRAIN_SYNC_REPLAY_REJECTED/, 'relay must reject sequence rewrites');
assert.match(mobileSync, /BRAIN_SYNC_CONFLICT/, 'relay must stop on a stale desktop cursor');
assert.match(mobileSync, /idempotent_replay/, 'relay must recognize an already-committed request id');
assert.match(mnemeBootstrap, /requireBrainOwner/, 'profile bootstrap must require the verified owner allowlist');
assert.match(mnemeBootstrap, /deriveMemberProfileId\(owner\.user\.id\)/, 'profile bootstrap identity must be server-derived');
assert.match(mnemeBootstrap, /BRAIN_MNEME_PROFILE_BINDING_MISMATCH/, 'profile bootstrap must refuse an existing mismatched binding');
assert.doesNotMatch(mnemeBootstrap, /profile_id:/, 'profile bootstrap must not return the opaque profile id');
assert.equal(brainManifest.id, '/apocrypha', 'installed Mini Brain identity is the private primary route');
assert.equal(brainManifest.start_url, '/apocrypha?source=installed-mini-brain', 'installed Mini Brain opens the private route');
assert.match(brainWorker, /url\.pathname\.startsWith\('\/api\/'\)\) return/, 'service worker must never cache private API responses');
assert.match(brainWorker, /url\.pathname === '\/apocrypha'/, 'service worker may cache only the private route shell');
assert.doesNotMatch(brainWorker, /clients\.claim/, 'service worker must not seize the first owner page before its authenticated requests complete');

console.log('brain-page.test : OK · owner gate + private projections + encrypted Mini Brain + signed sync seam');
