import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const read = (path: string): string => readFileSync(resolve(process.cwd(), path), 'utf8');

const page = read('pages/brain.tsx');
const apocryphaPage = read('pages/apocrypha.tsx');
const experience = read('components/brain/BrainExperience.tsx');
const owner = read('lib/brain/owner.ts');
const snapshot = read('pages/api/brain/snapshot.ts');
const runtimeProvider = read('lib/brain/runtime-provider.ts');
const runtimeProxy = read('lib/apocv4/runtime-proxy.ts');
const middleware = read('middleware.ts');
const telemetry = read('lib/akashic-telemetry/client.ts');
const app = read('pages/_app.tsx');
const home = read('pages/index.tsx');
const shell = read('components/SiteShell.tsx');
const document = read('pages/_document.tsx');
const consent = read('components/AkashicConsent.tsx');
const siteSession = read('components/hub/SiteSession.tsx');
const miniBrain = read('lib/brain/mini-brain.ts');
const mobileRelay = read('lib/brain/mobile-relay.ts');
const mobileRelayState = read('lib/brain/mobile-relay-state.ts');
const mobileSync = read('pages/api/brain/mobile/sync.ts');
const mnemeBootstrap = read('pages/api/brain/mneme/bootstrap.ts');
const brainManifest = JSON.parse(read('public/brain-manifest.json')) as Record<string, unknown>;
const brainWorker = read('public/brain-sw.js');

assert.match(page, /getServerSideProps/, 'Brain page must authorize before render');
assert.match(page, /requireBrainOwner/, 'Brain page must use the owner allowlist boundary');
assert.match(page, /private, no-store/, 'Brain document must be private and non-cacheable');
assert.match(page, /noindex,nofollow,noarchive,nosnippet/, 'Brain page must be crawler-dark');
assert.match(apocryphaPage, /getServerSideProps/, 'primary Apocrypha page must authorize before render');
assert.match(apocryphaPage, /requireBrainOwner/, 'primary Apocrypha page must use the same owner allowlist boundary');
assert.match(apocryphaPage, /<BrainExperience serverAccess=\{serverAccess\} \/>/, 'primary route must render the existing Brain experience');
assert.match(apocryphaPage, /<title>Apocrypha · Apocky<\/title>/, 'primary route must carry Apocrypha branding');
assert.match(apocryphaPage, /Persistent owner-private Apocrypha conversation/, 'primary route must describe its private conversation honestly');
assert.match(apocryphaPage, /private, no-store/, 'primary Apocrypha document must be private and non-cacheable');
assert.match(apocryphaPage, /noindex,nofollow,noarchive,nosnippet/, 'primary Apocrypha page must be crawler-dark');
assert.match(apocryphaPage, /destination: '\/login\?next=%2Fapocrypha'/, 'sign-in must return to the primary Apocrypha route');
assert.match(apocryphaPage, /apple-mobile-web-app-capable" content="yes"/, 'primary route must opt into the iOS installed surface');
assert.match(apocryphaPage, /viewport-fit=cover/, 'primary route must expose iOS safe-area insets');
assert.match(page, /viewport-fit=cover/, 'legacy private route must expose iOS safe-area insets');
assert.doesNotMatch(apocryphaPage, /rel="manifest"/, 'primary route must not add a second manifest link');
assert.doesNotMatch(page, /rel="manifest"/, 'legacy Brain route must not add a second manifest link');
assert.doesNotMatch(document, /rel="manifest"/, 'the static document must not retain a stale manifest across client navigation');
assert.match(app, /router\.pathname === '\/apocrypha' \|\| router\.pathname === '\/brain'/, 'app must select the Mini Brain manifest from the live route');
assert.match(app, /privateBrainManifest \? '\/brain-manifest\.json' : '\/manifest\.json'/, 'app must emit exactly one route-specific manifest link');
assert.match(owner, /getAdminAuthorization/, 'Brain APIs must derive authority from the server session');
assert.match(owner, /BRAIN_OWNER_REQUIRED/, 'non-owner identities must have a stable denial code');
assert.match(snapshot, /deriveMemberProfileId\(owner\.user\.id\)/, 'snapshot profile must be derived server-side');
assert.doesNotMatch(snapshot, /profile_id:/, 'snapshot must not emit a profile identifier');
assert.match(snapshot, /getMessagesByIds/, 'source references must resolve through the private store');
assert.match(experience, /CONTEXTUAL RECALL · NO MODEL CALL/, 'contextual recall must disclose its deterministic path');
assert.match(experience, /<p>OWNER-PRIVATE BRAIN<\/p><h1>Apocrypha<\/h1>/, 'shared experience must visibly identify Apocrypha');
assert.match(experience, /BrainGraph/, 'graph projection missing');
assert.match(experience, /Timeline/, 'timeline projection missing');
assert.match(experience, /Tunnel/, 'source tunnel missing');
assert.match(experience, /sourceMessages\(memory, messages\)/, 'tunnel must bind memory source IDs to message records');
assert.doesNotMatch(experience, /\/api\/mneme\//, 'browser must use only owner-authorized Brain APIs');
assert.doesNotMatch(experience, /ANTHROPIC|VOYAGE|retrievePipeline/, 'new Brain turns must not invoke paid model paths');
assert.match(runtimeProvider, /submitOwnerBrainRuntimeChat/, 'conversation must use the validated local runtime adapter');
assert.match(runtimeProxy, /APOCKY_BRAIN_LOCAL_PROVIDER_ENABLED/, 'local runtime needs an explicit scoped enable gate');
assert.match(runtimeProxy, /owner-brain/, 'runtime bypass must be scoped to the Brain adapter');
assert.match(middleware, /request\.nextUrl\.pathname === '\/brain'/, 'middleware must recognize the private page');
assert.match(middleware, /request\.nextUrl\.pathname === '\/apocrypha'/, 'middleware must recognize the primary private alias');
assert.match(telemetry, /pathname === '\/brain'/, 'private page must be a telemetry blackout');
assert.match(telemetry, /pathname === '\/apocrypha'/, 'primary private alias must be a telemetry blackout');
assert.match(app, /pathname === '\/apocrypha'/, 'primary private alias must render without the public site shell');
assert.match(home, /access === 'owner'[\s\S]*?href: '\/apocrypha'/, 'home must send owner access to the primary Apocrypha route');
assert.match(home, /href: authenticated \? '\/apocrypha' : '\/login\?next=%2Fapocrypha'/, 'home sign-in must return to the primary route');
assert.match(shell, /access === 'owner'.*href="\/apocrypha"/, 'shell must reveal the primary route only after owner authorization');
assert.match(experience, /Mini Brain · deterministic/, 'offline response must not impersonate learned Apocrypha');
assert.match(experience, /desktop remains authoritative/i, 'mobile topology must name desktop authority');
assert.match(experience, /Retry on current history/, 'cursor conflict requires an explicit owner rebase');
assert.match(experience, /Create my private memory profile/, 'missing Mneme profile needs an explicit owner action');
assert.match(experience, /CREATE_OWNER_PRIVATE_MNEME_PROFILE/, 'profile bootstrap must carry an exact confirmation value');
assert.match(experience, /loadInFlightRef\.current/, 'resume synchronization must not overlap an existing load');
assert.match(experience, /reloadPendingRef\.current = true/, 'a refresh arriving during load must be drained rather than dropped');
assert.match(experience, /setLoading\(false\);[\s\S]*?if \(remoteOwnerReady && serverAccess === 'owner'/, 'local vault readiness must render before remote binding and projection work');
assert.match(experience, /siteAccess === 'checking'/, 'local vault opening must wait for the current browser subject before decrypting offline state');
assert.match(experience, /window\.addEventListener\('storage', storageLocked\)/, 'cross-tab logout must retain a native storage-event fallback when BroadcastChannel is absent');
assert.match(experience, /useLayoutEffect\(\(\) => \{[\s\S]*?LOCK_MINI_BRAIN_ACK/, 'service-worker lock acknowledgement must wait for the private DOM-clearing commit boundary');
assert.match(experience, /persistedSessionLockStillAuthorized\(\)/, 'visible private clients must re-read IndexedDB authority after missed cross-context signals');
assert.match(experience, /setInterval\(\(\) => \{ void inspectAuthority\(false\); \}, 1_000\)/, 'visible private presentation must poll the persisted authorization boundary at a bounded cadence');
assert.match(experience, /apocky-mini-brain-lock-unconfirmed/, 'simultaneous durable-storage failure must replace the ordinary locked claim with a truthful warning');
assert.match(experience, /vault\.sessionLockStillAuthorized\(\)/, 'focus and page-cache resume must recheck the durable lock epoch after missed events');
assert.match(experience, /presentedSubjectRef\.current === subjectKey/, 'private JSX must be synchronously fenced to the currently resolved browser subject');
assert.match(experience, /EDGE_READ_TIMEOUT_MS = 12_000/, 'remote edge reads must have a bounded wait');
assert.match(experience, /APPEND_TIMEOUT_MS = 185_000/, 'long local-model append has an explicit client-stage budget');
assert.match(experience, /let vault = vaultRef\.current/, 'resume synchronization must reuse the open IndexedDB connection');
assert.match(experience, /vaultRef\.current\?\.close\(\)/, 'component teardown must close its IndexedDB connection');
assert.match(experience, /vault\.withSyncLock\(async \(\) => \{[\s\S]*?jsonRequest<MiniBrainDeviceRegistration>/, 'device binding must share the cross-tab mutation lock');
assert.match(experience, /vault\.withSyncLock\(\(\) => vault\.freshState\(\)\)/, 'initial state creation must share the cross-tab mutation lock');
assert.match(experience, /vault\.withSyncLock\(async \(\) => \{[\s\S]*?vault\.cacheSnapshot/, 'snapshot caching must merge under the cross-tab mutation lock');
assert.match(experience, /document\.addEventListener\('visibilitychange', resume\)/, 'visible iOS resume must refresh the shared worldline');
assert.match(experience, /window\.addEventListener\('pageshow', resume\)/, 'page-cache resume must refresh the shared worldline');
assert.ok(experience.indexOf('className={styles.layout}') < experience.indexOf('className={styles.systemDrawer}'), 'conversation must precede optional system and release detail');
assert.match(consent, /if \(blackout \|\| compactSurface\) return null/, 'privacy-blackout pages must not render a diagnostics control over the conversation');
assert.match(miniBrain, /AES-GCM/, 'recent local state must be encrypted');
assert.match(miniBrain, /MINI_BRAIN_SESSION_LOCK_STORAGE_UNAVAILABLE/, 'unreadable durable lock storage must fail closed with a typed state');
assert.match(miniBrain, /MINI_BRAIN_LOCK_DURABILITY_UNCONFIRMED/, 'simultaneous lock-media failure must remain typed instead of becoming a false durable-success claim');
assert.match(miniBrain, /boundedLockSideEffect/, 'storage and shell side effects must not hold a valid site login forever');
assert.match(miniBrain, /LOCK_BOUNDARY_KEY = 'lock-boundary'/, 'rebind authority must use a persistent boundary independent of device creation');
assert.match(miniBrain, /store\.put\(\{ key: LOCK_BOUNDARY_KEY, generation: boundaryGeneration \}/, 'every lock must persist its generation before a candidate can authorize a bind');
assert.match(miniBrain, /boundary\?\.generation !== authorizedLockGeneration/, 'the identity bind transaction must recheck the current persisted boundary');
assert.match(miniBrain, /lockGeneration === null \|\| vault\.authorizedLockGeneration !== lockGeneration/, 'a missing browser lock must never equal a revoked null authorization');
assert.match(miniBrain, /peerRelayConfirmed !== true/, 'an existing private identity requires acknowledged live-peer invalidation');
assert.doesNotMatch(miniBrain, /return 'locked'/, 'a storage error sentinel must never become an authorizable lock generation');
assert.match(siteSession, /requestGenerationRef/, 'session resolution must enforce latest-wins ordering across mount, auth, and manual refresh');
assert.match(siteSession, /activeProbeRef\.current\?\.abort/, 'a newer authority probe must abort the older network work');
assert.match(siteSession, /requestGenerationRef\.current !== generation/, 'a stale completion must never overwrite newer owner evidence');
assert.match(miniBrain, /extractable|false,[\s\S]*?\['sign', 'verify'\]/, 'device private signing key must be non-exportable');
assert.match(miniBrain, /NO_VERIFIED_LOCAL_MODEL_ARTIFACT/, 'unavailable learned cortex must remain typed and truthful');
assert.doesNotMatch(miniBrain, /snapshot\.messages/, 'offline memory cache must not copy raw Mneme source messages');
assert.match(miniBrain, /pendingLocalMessages/, 'a remote cursor conflict must not hide the still-queued local turn');
assert.match(mobileRelay, /ECDSA/, 'relay must verify the device signature');
assert.match(mobileRelayState, /BRAIN_SYNC_REPLAY_REJECTED/, 'durable relay admission must reject sequence rewrites');
assert.match(mobileSync, /admitVerifiedMiniBrainRequest\(dependencies\.relayState\(\), signed\)/, 'sync route must admit every request through the durable replay boundary');
assert.match(mobileSync, /BRAIN_SYNC_CONFLICT/, 'relay must stop on a stale desktop cursor');
assert.match(mobileSync, /idempotent_replay/, 'relay must recognize an already-committed request id');
assert.match(mobileSync, /ownerBrainRuntimeRequestId/, 'mobile receipt verification must use the server-scoped runtime request id');
assert.match(mobileSync, /acknowledgedRequestIds: \[request\.request_id\]/, 'bounded session projections must still carry a durable runtime acknowledgement');
assert.match(miniBrain, /response\.acknowledged_request_ids/, 'a durable acknowledgement must clear an aged queued request even when messages are projection-bounded');
assert.match(mnemeBootstrap, /requireBrainOwner/, 'profile bootstrap must require the verified owner allowlist');
assert.match(mnemeBootstrap, /deriveMemberProfileId\(owner\.user\.id\)/, 'profile bootstrap identity must be server-derived');
assert.match(mnemeBootstrap, /BRAIN_MNEME_PROFILE_BINDING_MISMATCH/, 'profile bootstrap must refuse an existing mismatched binding');
assert.doesNotMatch(mnemeBootstrap, /profile_id:/, 'profile bootstrap must not return the opaque profile id');
assert.equal(brainManifest.id, '/apocrypha', 'installed Mini Brain identity is the private primary route');
assert.equal(brainManifest.start_url, '/apocrypha?source=installed-mini-brain', 'installed Mini Brain opens the private route');
assert.match(brainWorker, /url\.pathname\.startsWith\('\/api\/'\)\) return/, 'service worker must never cache private API responses');
assert.match(brainWorker, /url\.pathname === '\/apocrypha'/, 'service worker may cache only the private route shell');
assert.match(brainWorker, /!response\.redirected/, 'service worker must never cache a followed sign-in redirect as the Brain shell');
assert.match(brainWorker, /html\.includes\('\"serverAccess\":\"owner\"'\)/, 'service worker must verify the owner shell marker before caching');
assert.match(brainWorker, /clients\.matchAll\(\{ type: 'window', includeUncontrolled: true \}\)/, 'lock relay must enumerate every current private window client');
assert.match(brainWorker, /pending\.expected\.delete\(sourceId\)/, 'lock relay must accept acknowledgements only from enumerated client identities');
assert.match(brainWorker, /pending\.resolve\(status === 'acknowledged'\)/, 'the service-worker lifetime must remain attached until every private client acknowledges or times out');
assert.doesNotMatch(brainWorker, /void caches\.open/, 'service-worker cache writes must remain attached to the fetch lifetime');
assert.doesNotMatch(brainWorker, /clients\.claim/, 'service worker must not seize the first owner page before its authenticated requests complete');
assert.match(miniBrain, /apocky-mini-brain-shell-v2/, 'browser vault helpers must use the current Mini Brain shell cache');
assert.match(brainWorker, /apocky-mini-brain-shell-v2/, 'service worker must use the same Mini Brain shell cache generation');
assert.match(miniBrain, /key\.startsWith\('apocky-mini-brain-shell-'\)/, 'erase must remove every Mini Brain shell cache generation');
assert.match(miniBrain, /reserveSigningIdentity/, 'device sequence allocation must be an IndexedDB transaction rather than a stale in-memory increment');
assert.match(miniBrain, /SYNC_LEASE_KEY/, 'mutating sync work must share a browser-profile lease across tabs and installed mode');
assert.match(miniBrain, /database\.onversionchange = \(\) => this\.database\.close\(\)/, 'other tabs must release IndexedDB when an erase requests a version change');
assert.match(miniBrain, /CLOSE_MINI_BRAIN_DATABASE/, 'erase must notify other same-origin tabs before deleting the vault');
assert.match(experience, /state === 'erased'/, 'erase UI must distinguish complete deletion from a blocked database deletion');
assert.match(miniBrain, /shell\.clone\(\)\.text\(\)/, 'manual warm must inspect a clone without consuming the cacheable network response');
assert.match(miniBrain, /cache\.put\('\/apocrypha', shell\.clone\(\)\)/, 'manual warm must cache the untouched response with coherent encoding headers');

console.log('brain-page.test : OK · owner gate + private projections + encrypted Mini Brain + signed sync seam');
