import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Marked } from 'marked';

const ROOT=path.dirname(fileURLToPath(import.meta.url));
const PUBLIC=path.resolve(ROOT,'../../public/codex-apockalypsis');
const args=process.argv.slice(2);
if(args.length && (args.length!==2 || args[0]!=='--out')) throw new Error('Usage: node build.mjs [--out DIRECTORY]');
const OUT=args.length?path.resolve(args[1]):PUBLIC;
if(args.length && fs.existsSync(OUT) && fs.readdirSync(OUT).length) throw new Error('The custom output directory must be empty.');
const BASE='/codex-apockalypsis';
const data=JSON.parse(fs.readFileSync(path.join(PUBLIC,'content.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>/^(https?:\/\/|\/(?!\/)|#)/i.test(String(s??''))?String(s):null;
const labels={novel:'Novel',codex:'Codex',reference:'Reference',planning:'Plans',calibration:'Voice study'};
const docs=data.documents;
const slugs=new Set();
for(const d of docs){
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.slug)||slugs.has(d.slug)) throw new Error('Document slugs must be unique lowercase URL segments.');
  slugs.add(d.slug);
}
const href=d=>`${BASE}/library/${d.slug}`;
let activeToc=[], headingIds=new Map();
const marked=new Marked({gfm:true,breaks:false,renderer:{
  html({text}){return esc(text);},
  link({href,title,tokens}){const u=safeUrl(href);const t=this.parser.parseInline(tokens);return u?`<a href="${esc(u)}"${title?` title="${esc(title)}"`:''}${/^https?:/i.test(u)?' rel="noopener noreferrer"':''}>${t}</a>`:t;},
  image({href,text}){const u=safeUrl(href);return u?`<img src="${esc(u)}" alt="${esc(text)}" loading="lazy">`:esc(text);},
  heading({tokens,depth}){const plain=tokens.map(t=>t.text??'').join('');const base=plain.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'section';const count=headingIds.get(base)||0;headingIds.set(base,count+1);const id=base+(count?`-${count+1}`:'');if(depth<=3)activeToc.push(`<a href="#${esc(id)}">${esc(plain)}</a>`);return `<h${depth} id="${esc(id)}">${this.parser.parseInline(tokens)}</h${depth}>`;}
}});
function shell({title,description,canonical=BASE,body,reader=false}){
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark light"><title>${esc(title)} · Apocky</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://www.apocky.com${canonical}"><meta property="og:type" content="${reader?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="https://www.apocky.com${canonical}"><meta property="og:image" content="https://www.apocky.com${BASE}/maps/01_omnoid_topology.png"><link rel="stylesheet" href="${BASE}/assets/codex.css"><script defer src="${BASE}/assets/codex.js"></script></head><body class="${reader?'reading-page':''}"><a class="skip" href="#main-content">Skip to content</a><header class="masthead"><a class="wordmark" href="/" aria-label="Apocky home">APOCKY<span class="brand-star" aria-hidden="true">✧</span></a><a class="publication-name" href="${BASE}">Codex Apockalypsis</a><nav aria-label="Publication"><a href="${BASE}#reading">Read</a><a href="${BASE}#library">Library</a><a href="${BASE}#atlas">Atlas</a><a href="${BASE}#sources">Sources</a></nav></header>${body}<footer class="footer"><div><a class="wordmark" href="/">APOCKY</a><p>Stories, questions, and the work of remembering.</p></div><div><a href="${BASE}">Codex Apockalypsis</a><a href="/atlas">Explore Apocky</a><a href="/legal/terms">Terms</a><a href="/legal/privacy">Privacy</a></div><p class="fine">© 2026 Shawn Wolfgang Michael Baker · A developing work of fiction and commentary.</p></footer></body></html>`;
}
function card(d){return `<article class="document-card" data-document data-category="${esc(d.category)}" data-search="${esc((d.title+' '+d.description+' '+d.category).toLowerCase())}"><span class="eyebrow">${esc(labels[d.category]??d.category)}${d.category==='planning'?' · Spoilers':''}</span><h3><a href="${href(d)}">${esc(d.title)}</a></h3><p>${esc(d.description)}</p><a class="text-link" href="${href(d)}">Open text <span aria-hidden="true">↗</span></a></article>`;}
const novel=docs.find(d=>d.category==='novel');
const codex=docs.find(d=>d.category==='codex');
const lilith=docs.find(d=>/lilith/i.test(d.slug+' '+d.title));
const chapterCount=data.volumes.reduce((n,v)=>n+Number(v.chapterCount??0),0);
const maps=data.maps.map(m=>`<figure class="map-card"><a href="${esc(m.src.replace(/\.png$/,'.svg'))}" aria-label="Open full ${esc(m.title)}"><img src="${esc(m.src)}" alt="${esc(m.title)}" loading="lazy" width="1200" height="780"></a><figcaption><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p><a class="text-link" href="${esc(m.src.replace(/\.png$/,'.svg'))}">Explore full map ↗</a></figcaption></figure>`).join('');
const chapterRows=data.volumes.map((v,i)=>`<details class="volume"><summary><span class="volume-number">${String(i+1).padStart(2,'0')}</span><span>${esc(v.title)}</span><span class="volume-count">${v.chapterCount} outlined</span><span class="plus" aria-hidden="true">+</span></summary><p>${esc(v.summary)}</p></details>`).join('');
const sourceRows=data.sources.map(s=>`<tr data-source data-search="${esc((s.title+' '+s.tradition+' '+s.id).toLowerCase())}"><th scope="row">${safeUrl(s.url)?`<a href="${esc(s.url)}" rel="noopener noreferrer">${esc(s.title)} ↗</a>`:esc(s.title)}</th><td>${esc(s.tradition)}</td><td>${esc(Array.isArray(s.volumes)?s.volumes.join(', '):s.volumes)}</td><td>${esc(String(s.status).replaceAll('_',' '))}</td></tr>`).join('');
const downloads=(data.downloads??[]).map(d=>`<a class="download-item ${d.format==='ZIP'?'archive':''}" href="${esc(d.href)}" download><span>${esc(d.title)}</span><strong>${esc(d.format)} ↓</strong></a>`).join('');
const body=`<main id="main-content"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow">The Good Book · A new telling</p><h1>Codex<br><em>Apockalypsis.</em></h1><p class="hero-lead">Before the word.<br>After the certainty.</p><p class="hero-description">Sacred stories become dark fantasy, dark comedy, and a history big enough to argue with itself. A novel cycle and a parallel Codex, within the Omnoid.</p><div class="actions"><a class="button gold" href="${novel?href(novel):'#library'}">Begin reading <span aria-hidden="true">↗</span></a><a class="button quiet" href="#library">Explore the library</a></div><p class="byline">By Shawn Wolfgang Michael Baker <span>·</span> Work in progress</p></div><aside class="opening-leaf" aria-label="From the opening chapter"><div class="leaf-ornament" aria-hidden="true">✧</div><p class="eyebrow">I · Before the Word</p><blockquote>There was no one to tell the dark that it was empty.</blockquote><p>This was fortunate. The dark had a great deal in it, and explaining the inventory would have delayed creation considerably.</p><a href="${novel?href(novel):'#library'}">Before Anyone Asked <span aria-hidden="true">→</span></a><div class="leaf-mark" aria-hidden="true">I</div></aside></section><div class="rule wrap"><span>Fiction</span><i></i><span>Commentary</span><i></i><span>Cosmology</span></div>
<section id="reading" class="wrap section"><div class="section-heading"><div><p class="eyebrow">Two ways into one developing history</p><h2>The story. The margins.</h2></div><p>Follow the lives in the novel. Read beside them in the Codex, where scripture, testimony, questions, and historical notes share the page.</p></div><div class="edition-grid"><article class="edition"><span class="edition-no">01 / NOVEL</span><h3>Before Anyone Asked</h3><p>The Mother is not empty. The First Flame is not alone. Recognising either fact will take considerably more than light.</p><a class="text-link" href="${novel?href(novel):'#library'}">Read the opening chapter ↗</a></article><article class="edition"><span class="edition-no">02 / CODEX</span><h3>The Unanswered Interval</h3><p>The same encounter, in original scripture and commentary. What the telling inherits, what it changes, and what remains unsettled.</p><a class="text-link" href="${codex?href(codex):'#library'}">Read the paired Codex ↗</a></article></div><div class="lilith-note"><span aria-hidden="true">✧</span><div><h3>And Lilith?</h3><p>Her refusal is a beginning. Her protective role, her relationship with the Mother, and her life beyond the Garden have a story of their own.</p></div><a class="text-link" href="${lilith?href(lilith):'#library'}">Find Lilith ↗</a></div><p class="scope-note">Currently available: one drafted novel chapter and its paired Codex, a twelve-volume outline, and the developing reference collection. Planning documents discuss future events and contain spoilers.</p></section>
<section id="library" class="library-section section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">The collected work</p><h2>Enter the library.</h2></div><div class="search-field"><label for="library-search">Find a text</label><input type="search" id="library-search" placeholder="Try Lilith, creation, or chronology…" autocomplete="off"></div></div><div class="filters" role="group" aria-label="Filter library"><button type="button" data-filter="all" aria-pressed="true">Everything</button>${Object.entries(labels).map(([k,v])=>`<button type="button" data-filter="${k}" aria-pressed="false">${v}</button>`).join('')}</div><p class="result-count" id="library-count" role="status">${docs.length} texts</p><div class="document-grid">${docs.map(card).join('')}</div><p class="empty" id="library-empty" hidden>No texts match. Try another word or choose Everything.</p></div></section>
<section id="series" class="wrap section"><div class="section-heading"><div><p class="eyebrow">The novel cycle</p><h2>Twelve volumes.<br>A history still unfolding.</h2></div><p>From creation and the first refusal to kingdoms, exile, witnesses, and the return of names. ${chapterCount?chapterCount+' chapter designs are currently outlined.':'The chapter outline is developing.'} These are plans for the full cycle.</p></div><div class="volume-grid">${chapterRows}</div></section>
<section id="atlas" class="wrap section"><div class="section-heading"><div><p class="eyebrow">Places, passages, and different clocks</p><h2>An atlas of the unfinished.</h2></div><p>Conceptual realms, historical settings, and parallel chronologies. Each map names its limits: a symbolic relationship is not a measured distance.</p></div><div class="atlas-grid">${maps}</div></section>
<section id="sources" class="sources-section section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">Witnesses behind the telling</p><h2>A source is a beginning.</h2></div><p>The fiction weaves traditions into a shared history. The notes preserve their real differences. ${data.sources.length} catalogue records identify works, collections, or research families; they do not claim that every text has been fully read.</p></div><details class="source-details"><summary>Browse the source concordance <span>${data.sources.length} records +</span></summary><div class="source-tools"><label for="source-search">Find a source or tradition</label><input type="search" id="source-search" placeholder="Genesis, Nag Hammadi, wisdom…" autocomplete="off"><p id="source-count" role="status">${data.sources.length} records</p></div><div class="table-scroll" tabindex="0" role="region" aria-label="Source catalogue"><table><thead><tr><th>Work or collection</th><th>Tradition / collection</th><th>Planned volumes</th><th>Research status</th></tr></thead><tbody>${sourceRows}</tbody></table></div><p id="source-empty" hidden>No sources match this search.</p></details></div></section>
<section id="downloads" class="wrap section"><div class="section-heading"><div><p class="eyebrow">Take the pages with you</p><h2>Reading copies.</h2></div><p>The library is readable here. Individual texts also offer Markdown downloads, and the collection is available as a public archive.</p></div><div class="downloads">${downloads}</div></section></main>`;

fs.mkdirSync(OUT,{recursive:true});
if(OUT!==PUBLIC) fs.cpSync(PUBLIC,OUT,{recursive:true});
fs.mkdirSync(path.join(OUT,'assets'),{recursive:true});
fs.copyFileSync(path.join(ROOT,'codex.css'),path.join(OUT,'assets/codex.css'));
fs.copyFileSync(path.join(ROOT,'codex.js'),path.join(OUT,'assets/codex.js'));
fs.writeFileSync(path.join(OUT,'index.html'),shell({title:'Codex Apockalypsis',description:'The Good Book: a dark fantasy and dark comedy novel cycle, parallel Codex, atlas, and source library within the Omnoid.',body}));

for(const [i,d] of docs.entries()){
 activeToc=[];headingIds=new Map();const rendered=marked.parse(d.body);const toc=activeToc;
 const supplementary=d.category!=='novel'&&d.category!=='codex'&&d.slug!=='reference-reading-v01-c01'&&d.slug!=='start-here';
 const editionLinks=(d.downloads??[]).map(x=>`<a class="text-link" href="${esc(x.href)}" download>Download ${esc(x.format)} ↓</a>`).join('');
 const related=d.category==='novel'?codex:d.category==='codex'?novel:null;
 const reading=`<main id="main-content" class="reader wrap"><div class="reader-top"><a href="${BASE}#library">← The library</a><span>${esc(labels[d.category]??d.category)} · Developing edition</span><div class="reader-controls"><button id="reader-theme" type="button" aria-pressed="false">Paper view</button><button id="reader-size" type="button" aria-pressed="false">Larger type</button></div></div>${supplementary?'<p class="reader-notice">Development notes · May reveal planned events and unresolved proposals.</p>':''}<div class="reader-layout"><aside class="contents"><details open><summary>On this page</summary><nav aria-label="In this text">${toc.join('')}</nav></details><a class="text-link" href="${esc(d.downloadPath)}" download>Download Markdown ↓</a>${editionLinks}${related?`<a class="text-link" href="${href(related)}">Read the ${esc(labels[related.category])} ↗</a>`:''}</aside><article class="prose" aria-label="${esc(d.title)}">${rendered}</article></div><div class="reader-end"><a class="button quiet" href="${BASE}#library">Return to the library</a>${related?`<a class="button gold" href="${href(related)}">Read beside this chapter ↗</a>`:''}</div></main>`;
 const f=path.join(OUT,'library',d.slug,'index.html');fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,shell({title:d.title,description:d.description,canonical:href(d),reader:true,body:reading}));
}
console.log(JSON.stringify({site:OUT,documents:docs.length,sources:data.sources.length,chapterCount}));
